[package]
name = "calico"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chrono = { version = "0.4.41", default-features = false }
iri-string = "0.7.8"
winnow = "0.7.10"

[features]
memchr = ["winnow/simd", "iri-string/memchr"]
