[package]
name = "calico"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.41"
http = "1.3.1"
iri-string = { version = "0.7.8", features = ["memchr"] }
mime = "0.3.17"
oxilangtag = "0.1.5"
uuid = { version = "1.17.0", features = ["v4"] }
winnow = "0.7.10"
