[package]
name = "calico"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
http = "1.3.1"
iri-string = { version = "0.7.8", features = ["memchr"] }
oxilangtag = "0.1.5"
winnow = "0.7.10"
