//! CSS3 color names.

/// CSS3 colors as defined by [the W3C recommendation.](https://www.w3.org/TR/css-color-3/)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Css3Color {
    AliceBlue,
    AntiqueWhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    BlanchedAlmond,
    Blue,
    BlueViolet,
    Brown,
    BurlyWood,
    CadetBlue,
    Chartreuse,
    Chocolate,
    Coral,
    CornflowerBlue,
    Cornsilk,
    Crimson,
    Cyan,
    DarkBlue,
    DarkCyan,
    DarkGoldenRod,
    DarkGray,
    DarkGrey,
    DarkGreen,
    DarkKhaki,
    DarkMagenta,
    DarkOliveGreen,
    DarkOrange,
    DarkOrchid,
    DarkRed,
    DarkSalmon,
    DarkSeaGreen,
    DarkSlateBlue,
    DarkSlateGray,
    DarkSlateGrey,
    DarkTurquoise,
    DarkViolet,
    DeepPink,
    DeepSkyBlue,
    DimGray,
    DimGrey,
    DodgerBlue,
    FireBrick,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    GoldenRod,
    Gray,
    Grey,
    Green,
    GreenYellow,
    HoneyDew,
    HotPink,
    IndianRed,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    LavenderBlush,
    LawnGreen,
    LemonChiffon,
    LightBlue,
    LightCoral,
    LightCyan,
    LightGoldenRodYellow,
    LightGray,
    LightGrey,
    LightGreen,
    LightPink,
    LightSalmon,
    LightSeaGreen,
    LightSkyBlue,
    LightSlateGray,
    LightSlateGrey,
    LightSteelBlue,
    LightYellow,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Maroon,
    MediumAquaMarine,
    MediumBlue,
    MediumOrchid,
    MediumPurple,
    MediumSeaGreen,
    MediumSlateBlue,
    MediumSpringGreen,
    MediumTurquoise,
    MediumVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhite,
    Navy,
    OldLace,
    Olive,
    OliveDrab,
    Orange,
    OrangeRed,
    Orchid,
    PaleGoldenRod,
    PaleGreen,
    PaleTurquoise,
    PaleVioletRed,
    PapayaWhip,
    PeachPuff,
    Peru,
    Pink,
    Plum,
    PowderBlue,
    Purple,
    Red,
    RosyBrown,
    RoyalBlue,
    SaddleBrown,
    Salmon,
    SandyBrown,
    SeaGreen,
    SeaShell,
    Sienna,
    Silver,
    SkyBlue,
    SlateBlue,
    SlateGray,
    SlateGrey,
    Snow,
    SpringGreen,
    SteelBlue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    WhiteSmoke,
    Yellow,
    YellowGreen,
}

impl Css3Color {
    /// Returns the CSS3 color keyword corresponding to `self`.
    pub const fn as_str(&self) -> &'static str {
        match self {
            Css3Color::AliceBlue => "aliceblue",
            Css3Color::AntiqueWhite => "antiquewhite",
            Css3Color::Aqua => "aqua",
            Css3Color::Aquamarine => "aquamarine",
            Css3Color::Azure => "azure",
            Css3Color::Beige => "beige",
            Css3Color::Bisque => "bisque",
            Css3Color::Black => "black",
            Css3Color::BlanchedAlmond => "blanchedalmond",
            Css3Color::Blue => "blue",
            Css3Color::BlueViolet => "blueviolet",
            Css3Color::Brown => "brown",
            Css3Color::BurlyWood => "burlywood",
            Css3Color::CadetBlue => "cadetblue",
            Css3Color::Chartreuse => "chartreuse",
            Css3Color::Chocolate => "chocolate",
            Css3Color::Coral => "coral",
            Css3Color::CornflowerBlue => "cornflowerblue",
            Css3Color::Cornsilk => "cornsilk",
            Css3Color::Crimson => "crimson",
            Css3Color::Cyan => "cyan",
            Css3Color::DarkBlue => "darkblue",
            Css3Color::DarkCyan => "darkcyan",
            Css3Color::DarkGoldenRod => "darkgoldenrod",
            Css3Color::DarkGray => "darkgray",
            Css3Color::DarkGrey => "darkgrey",
            Css3Color::DarkGreen => "darkgreen",
            Css3Color::DarkKhaki => "darkkhaki",
            Css3Color::DarkMagenta => "darkmagenta",
            Css3Color::DarkOliveGreen => "darkolivegreen",
            Css3Color::DarkOrange => "darkorange",
            Css3Color::DarkOrchid => "darkorchid",
            Css3Color::DarkRed => "darkred",
            Css3Color::DarkSalmon => "darksalmon",
            Css3Color::DarkSeaGreen => "darkseagreen",
            Css3Color::DarkSlateBlue => "darkslateblue",
            Css3Color::DarkSlateGray => "darkslategray",
            Css3Color::DarkSlateGrey => "darkslategrey",
            Css3Color::DarkTurquoise => "darkturquoise",
            Css3Color::DarkViolet => "darkviolet",
            Css3Color::DeepPink => "deeppink",
            Css3Color::DeepSkyBlue => "deepskyblue",
            Css3Color::DimGray => "dimgray",
            Css3Color::DimGrey => "dimgrey",
            Css3Color::DodgerBlue => "dodgerblue",
            Css3Color::FireBrick => "firebrick",
            Css3Color::FloralWhite => "floralwhite",
            Css3Color::ForestGreen => "forestgreen",
            Css3Color::Fuchsia => "fuchsia",
            Css3Color::Gainsboro => "gainsboro",
            Css3Color::GhostWhite => "ghostwhite",
            Css3Color::Gold => "gold",
            Css3Color::GoldenRod => "goldenrod",
            Css3Color::Gray => "gray",
            Css3Color::Grey => "grey",
            Css3Color::Green => "green",
            Css3Color::GreenYellow => "greenyellow",
            Css3Color::HoneyDew => "honeydew",
            Css3Color::HotPink => "hotpink",
            Css3Color::IndianRed => "indianred",
            Css3Color::Indigo => "indigo",
            Css3Color::Ivory => "ivory",
            Css3Color::Khaki => "khaki",
            Css3Color::Lavender => "lavender",
            Css3Color::LavenderBlush => "lavenderblush",
            Css3Color::LawnGreen => "lawngreen",
            Css3Color::LemonChiffon => "lemonchiffon",
            Css3Color::LightBlue => "lightblue",
            Css3Color::LightCoral => "lightcoral",
            Css3Color::LightCyan => "lightcyan",
            Css3Color::LightGoldenRodYellow => "lightgoldenrodyellow",
            Css3Color::LightGray => "lightgray",
            Css3Color::LightGrey => "lightgrey",
            Css3Color::LightGreen => "lightgreen",
            Css3Color::LightPink => "lightpink",
            Css3Color::LightSalmon => "lightsalmon",
            Css3Color::LightSeaGreen => "lightseagreen",
            Css3Color::LightSkyBlue => "lightskyblue",
            Css3Color::LightSlateGray => "lightslategray",
            Css3Color::LightSlateGrey => "lightslategrey",
            Css3Color::LightSteelBlue => "lightsteelblue",
            Css3Color::LightYellow => "lightyellow",
            Css3Color::Lime => "lime",
            Css3Color::LimeGreen => "limegreen",
            Css3Color::Linen => "linen",
            Css3Color::Magenta => "magenta",
            Css3Color::Maroon => "maroon",
            Css3Color::MediumAquaMarine => "mediumaquamarine",
            Css3Color::MediumBlue => "mediumblue",
            Css3Color::MediumOrchid => "mediumorchid",
            Css3Color::MediumPurple => "mediumpurple",
            Css3Color::MediumSeaGreen => "mediumseagreen",
            Css3Color::MediumSlateBlue => "mediumslateblue",
            Css3Color::MediumSpringGreen => "mediumspringgreen",
            Css3Color::MediumTurquoise => "mediumturquoise",
            Css3Color::MediumVioletRed => "mediumvioletred",
            Css3Color::MidnightBlue => "midnightblue",
            Css3Color::MintCream => "mintcream",
            Css3Color::MistyRose => "mistyrose",
            Css3Color::Moccasin => "moccasin",
            Css3Color::NavajoWhite => "navajowhite",
            Css3Color::Navy => "navy",
            Css3Color::OldLace => "oldlace",
            Css3Color::Olive => "olive",
            Css3Color::OliveDrab => "olivedrab",
            Css3Color::Orange => "orange",
            Css3Color::OrangeRed => "orangered",
            Css3Color::Orchid => "orchid",
            Css3Color::PaleGoldenRod => "palegoldenrod",
            Css3Color::PaleGreen => "palegreen",
            Css3Color::PaleTurquoise => "paleturquoise",
            Css3Color::PaleVioletRed => "palevioletred",
            Css3Color::PapayaWhip => "papayawhip",
            Css3Color::PeachPuff => "peachpuff",
            Css3Color::Peru => "peru",
            Css3Color::Pink => "pink",
            Css3Color::Plum => "plum",
            Css3Color::PowderBlue => "powderblue",
            Css3Color::Purple => "purple",
            Css3Color::Red => "red",
            Css3Color::RosyBrown => "rosybrown",
            Css3Color::RoyalBlue => "royalblue",
            Css3Color::SaddleBrown => "saddlebrown",
            Css3Color::Salmon => "salmon",
            Css3Color::SandyBrown => "sandybrown",
            Css3Color::SeaGreen => "seagreen",
            Css3Color::SeaShell => "seashell",
            Css3Color::Sienna => "sienna",
            Css3Color::Silver => "silver",
            Css3Color::SkyBlue => "skyblue",
            Css3Color::SlateBlue => "slateblue",
            Css3Color::SlateGray => "slategray",
            Css3Color::SlateGrey => "slategrey",
            Css3Color::Snow => "snow",
            Css3Color::SpringGreen => "springgreen",
            Css3Color::SteelBlue => "steelblue",
            Css3Color::Tan => "tan",
            Css3Color::Teal => "teal",
            Css3Color::Thistle => "thistle",
            Css3Color::Tomato => "tomato",
            Css3Color::Turquoise => "turquoise",
            Css3Color::Violet => "violet",
            Css3Color::Wheat => "wheat",
            Css3Color::White => "white",
            Css3Color::WhiteSmoke => "whitesmoke",
            Css3Color::Yellow => "yellow",
            Css3Color::YellowGreen => "yellowgreen",
        }
    }
}
